export type ToolCategory = 'pdf' | 'image';
export type WasmDep = 'pdf-lib' | 'pdfjs' | 'mupdf' | 'image-wasm';

export interface ToolFaq {
  q: string;
  a: string;
}

export interface HowToStep {
  title: string;
  description: string;
}

export interface ToolDef {
  slug: string;
  name: string;
  shortDescription: string;
  longDescription: string;
  category: ToolCategory;
  icon: string;
  primaryKeyword: string;
  pageTitle: string;
  metaDescription: string;
  h1: string;
  relatedSlugs: string[];
  wasmDeps: WasmDep[];
  faqs: ToolFaq[];
  howToSteps: HowToStep[];
  features: string[];
}

export const TOOLS: ToolDef[] = [
  // ─── PDF TOOLS ─────────────────────────────────────────────────────────
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    shortDescription: 'Combine multiple PDFs into one',
    longDescription: 'Merge multiple PDF files into a single document. Drag to reorder pages, select specific page ranges per file, and preserve bookmarks and links.',
    category: 'pdf',
    icon: '/icons/tools/merge-pdf.svg',
    primaryKeyword: 'merge pdf',
    pageTitle: 'Merge PDF Files Online Free — No Upload | Docukit',
    metaDescription: 'Merge PDF files online for free. 100% browser-based — no uploads, no sign-up. Drag to reorder, select pages, preserve bookmarks. Private and instant.',
    h1: 'Merge PDF Files Online for Free',
    relatedSlugs: ['split-pdf', 'compress-pdf', 'rearrange-pdf-pages'],
    wasmDeps: ['pdf-lib', 'pdfjs'],
    faqs: [
      { q: 'Does Docukit upload my PDFs to a server?', a: 'No. All merging happens 100% in your browser using WebAssembly. Your files never leave your device.' },
      { q: 'How many PDFs can I merge at once?', a: 'Up to 50 PDF files. For very large batches, we recommend splitting into groups if you notice memory warnings.' },
      { q: 'Can I reorder pages from different PDFs?', a: 'Yes — expand any file card to see its page thumbnails and select exactly which pages to include, in what order.' },
      { q: 'Are encrypted PDFs supported?', a: 'Yes. You will be prompted to enter the password for any encrypted PDF before it can be merged.' },
    ],
    howToSteps: [
      { title: 'Upload your PDFs', description: 'Drop your PDF files into the upload area or click to browse. You can add up to 50 files.' },
      { title: 'Arrange and select pages', description: 'Drag files to reorder them. Expand any file to select specific pages. Set advanced options as needed.' },
      { title: 'Merge and download', description: 'Click "Merge & Download" — your combined PDF is ready in seconds, processed entirely in your browser.' },
    ],
    features: [
      'Drag-and-drop file reorder',
      'Per-file page selection',
      'Preserve bookmarks & internal links',
      'Optional blank page between documents',
      'Password-protected PDF support',
      'Up to 50 files, 200MB per file',
    ],
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    shortDescription: 'Split or extract pages from a PDF',
    longDescription: 'Split a PDF by page range, extract specific pages, or separate every page into individual files. Multiple split modes with visual page selection.',
    category: 'pdf',
    icon: '/icons/tools/split-pdf.svg',
    primaryKeyword: 'split pdf',
    pageTitle: 'Split PDF Online Free — Extract Pages | Docukit',
    metaDescription: 'Split PDF files online for free. Extract pages, split by range, or separate every page. 100% browser-based, no uploads.',
    h1: 'Split PDF Files Online for Free',
    relatedSlugs: ['merge-pdf', 'compress-pdf', 'rearrange-pdf-pages'],
    wasmDeps: ['pdf-lib', 'pdfjs'],
    faqs: [
      { q: 'What split modes are available?', a: 'Extract Pages, Split by Range, Split Every N Pages, Extract Each Page as Individual PDF, and Remove Pages.' },
      { q: 'Can I visually select which pages to extract?', a: 'Yes — a thumbnail grid lets you click to select pages. Shift+click selects a range, Ctrl+click toggles individual pages.' },
      { q: 'How does the output work for multiple splits?', a: 'Multiple ranges produce a ZIP file containing one PDF per range. Single-range extraction produces a single PDF.' },
      { q: 'Is there a page limit?', a: 'Docukit handles up to 500 pages reliably. For larger documents, processing may be slower depending on your device.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF file into the upload area or click to browse.' },
      { title: 'Choose split mode and pages', description: 'Select a split mode (Extract, Range, Every N, Each Page, Remove) and specify the pages using the visual grid or text input.' },
      { title: 'Split and download', description: 'Click "Split & Download" — get a single PDF or a ZIP of multiple PDFs, all processed in your browser.' },
    ],
    features: [
      '5 split modes',
      'Visual thumbnail page selector',
      'Text syntax: "1-5, 8, odd, even, last"',
      'ZIP output for multi-file splits',
      'Range input with live page count',
    ],
  },
  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    shortDescription: 'Reduce PDF file size',
    longDescription: 'Compress PDF files using lossless or lossy algorithms. Choose from preset levels or customize DPI, JPEG quality, and more for the perfect balance of size and quality.',
    category: 'pdf',
    icon: '/icons/tools/compress-pdf.svg',
    primaryKeyword: 'compress pdf',
    pageTitle: 'Compress PDF Online Free — Reduce File Size | Docukit',
    metaDescription: 'Compress PDF files online for free. Reduce file size by up to 90% with our browser-based compression. No uploads, no accounts.',
    h1: 'Compress PDF Files Online for Free',
    relatedSlugs: ['merge-pdf', 'split-pdf', 'crop-pdf'],
    wasmDeps: ['pdf-lib', 'pdfjs', 'mupdf'],
    faqs: [
      { q: 'How much will my PDF be compressed?', a: 'Lossless compression typically reduces size by 10–30%. Medium (default) achieves 40–70%. High compression can reach 60–90% reduction.' },
      { q: 'Will compression reduce visual quality?', a: 'Lossless mode maintains full quality. Medium and High modes re-encode images — use the side-by-side preview to check quality before downloading.' },
      { q: 'What is the Custom mode?', a: 'Custom lets you set the exact JPEG quality (1–100), DPI target, grayscale conversion, and font stripping for precise control.' },
      { q: 'Does this work for scanned PDFs?', a: 'Yes — scanned PDFs (which are essentially images) benefit significantly from image re-encoding compression.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF into the upload area or click to browse.' },
      { title: 'Choose compression level', description: 'Select Low (lossless), Medium, High, or Custom. Adjust settings and preview the quality comparison.' },
      { title: 'Compress and download', description: 'Click "Compress & Download" — see the before/after size savings and download your optimised PDF.' },
    ],
    features: [
      '4 compression levels including custom',
      'Side-by-side quality preview',
      'Before/after file size comparison',
      'Custom DPI and JPEG quality controls',
      'Grayscale conversion option',
    ],
  },
  {
    slug: 'rearrange-pdf-pages',
    name: 'Rearrange PDF Pages',
    shortDescription: 'Reorder, rotate, and delete PDF pages',
    longDescription: 'Visually rearrange PDF pages with drag and drop. Rotate pages, delete unwanted ones, insert blanks, and duplicate pages — all with full undo/redo support.',
    category: 'pdf',
    icon: '/icons/tools/rearrange-pdf-pages.svg',
    primaryKeyword: 'rearrange pdf pages',
    pageTitle: 'Rearrange PDF Pages Online Free | Docukit',
    metaDescription: 'Rearrange, rotate, and delete PDF pages online for free. Drag-and-drop page reorder with undo/redo. 100% browser-based, no uploads.',
    h1: 'Rearrange PDF Pages Online for Free',
    relatedSlugs: ['split-pdf', 'merge-pdf', 'crop-pdf'],
    wasmDeps: ['pdf-lib', 'pdfjs'],
    faqs: [
      { q: 'Can I undo page moves?', a: 'Yes — full undo/redo with Ctrl+Z / Ctrl+Shift+Z, up to 20 actions.' },
      { q: 'Can I rotate multiple pages at once?', a: 'Yes — select multiple pages with Ctrl+click or Shift+click, then rotate the entire selection.' },
      { q: 'Can I insert blank pages?', a: 'Yes — click the "+" button between any two thumbnails to insert a blank page.' },
      { q: 'Are my original page contents preserved?', a: 'Yes — only the order, rotation, and presence of pages is changed. Page content is not modified.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF file into the upload area.' },
      { title: 'Rearrange pages', description: 'Drag thumbnails to reorder. Rotate, delete, duplicate, or insert blank pages using the toolbar and hover controls.' },
      { title: 'Download the result', description: 'Click "Apply & Download" to get your rearranged PDF, processed entirely in your browser.' },
    ],
    features: [
      'Drag-and-drop page reorder',
      'Multi-select with Ctrl+click / Shift+click',
      'Rotate 90° CW/CCW per page or batch',
      'Insert blank pages anywhere',
      'Duplicate pages',
      'Undo/redo up to 20 actions',
      'Zoom control: 80 / 150 / 250px thumbnails',
    ],
  },
  {
    slug: 'sign-pdf',
    name: 'Sign PDF',
    shortDescription: 'Add a visual signature to your PDF',
    longDescription: 'Sign PDF documents with a hand-drawn, typed, or uploaded signature. Place it anywhere on any page with drag-and-drop precision. Add date stamps, initials, and text annotations.',
    category: 'pdf',
    icon: '/icons/tools/sign-pdf.svg',
    primaryKeyword: 'sign pdf online free',
    pageTitle: 'Sign PDF Online Free — No Upload | Docukit',
    metaDescription: 'Sign PDF files online for free. Draw, type, or upload your signature. Place it anywhere. 100% browser-based — your document never leaves your device.',
    h1: 'Sign PDF Files Online for Free',
    relatedSlugs: ['digital-signature-pdf', 'edit-pdf', 'protect-pdf'],
    wasmDeps: ['pdf-lib', 'pdfjs'],
    faqs: [
      { q: 'What signature methods are supported?', a: 'Draw with mouse or touch, type your name in a handwriting font, or upload an image of your signature (PNG/JPG/SVG with auto background removal).' },
      { q: 'Is this a legally binding signature?', a: 'Visual signatures apply an image of your signature. For legally binding cryptographic signatures (PKCS#7 / PAdES standard), use our Digital Signature tool.' },
      { q: 'Can I sign multiple pages?', a: 'Yes — place your signature on any page. Use multi-page batch mode to apply the same signature at the same position across multiple pages.' },
      { q: 'Is my signature saved anywhere?', a: 'Your signature is stored only in your browser\'s sessionStorage for the duration of your session. It is deleted when you close the tab.' },
    ],
    howToSteps: [
      { title: 'Create your signature', description: 'Draw, type, or upload your signature. Choose from handwriting fonts if typing.' },
      { title: 'Place it on your PDF', description: 'Click anywhere on a page preview to place your signature. Drag to reposition, resize with handles, adjust opacity.' },
      { title: 'Apply and download', description: 'Click "Apply & Download" — your signature is permanently embedded in the PDF.' },
    ],
    features: [
      'Draw, type, or upload signature',
      'Pressure-sensitive drawing (Apple Pencil / stylus)',
      'Auto background removal for uploaded images',
      '4 handwriting font options',
      'Drag-and-drop placement with resize/rotate',
      'Date stamp and initials support',
      'Multi-page batch placement',
    ],
  },
  {
    slug: 'digital-signature-pdf',
    name: 'Digital Signature PDF',
    shortDescription: 'Cryptographically sign PDFs (PKCS#7)',
    longDescription: 'Add a real, verifiable cryptographic digital signature to PDF documents using PKCS#7 / PAdES standard. Generate a self-signed certificate or use your own CA-issued certificate.',
    category: 'pdf',
    icon: '/icons/tools/digital-signature-pdf.svg',
    primaryKeyword: 'digital signature pdf',
    pageTitle: 'Digital Signature PDF Online Free — PKCS#7 | Docukit',
    metaDescription: 'Add a cryptographic digital signature to PDF files for free. Self-signed or CA certificates. PKCS#7 / PAdES standard. 100% browser-based, private.',
    h1: 'Digitally Sign PDF Online for Free',
    relatedSlugs: ['sign-pdf', 'protect-pdf', 'edit-pdf'],
    wasmDeps: ['pdf-lib', 'pdfjs'],
    faqs: [
      { q: 'What is the difference between a visual signature and a digital signature?', a: 'A visual signature is just an image stamped on the PDF. A digital signature is a cryptographic proof that verifies the signer\'s identity and proves the document was not modified after signing.' },
      { q: 'Can I use my own company certificate?', a: 'Yes — upload your .pfx or .p12 certificate file. Docukit will use your certificate\'s private key (entered via password) to sign the document. The private key never leaves your browser.' },
      { q: 'Will Adobe Acrobat show the signature as valid?', a: 'With a CA-issued certificate: green "Signature is valid" checkmark. With a self-signed certificate: yellow warning with "Identity not verified" but integrity is still confirmed.' },
      { q: 'Is my private key secure?', a: 'Yes — your private key exists only in browser memory during signing and is immediately garbage-collected afterward. It is never stored or transmitted.' },
    ],
    howToSteps: [
      { title: 'Choose your certificate', description: 'Generate a free self-signed certificate in-browser, or upload your existing .p12/.pfx certificate file.' },
      { title: 'Upload and configure', description: 'Upload your PDF, optionally place a visible signature image linked to the digital signature field.' },
      { title: 'Sign and download', description: 'Click "Sign & Download" — your PDF is cryptographically signed per PKCS#7 / PAdES standard.' },
    ],
    features: [
      'PKCS#7 / PAdES standard digital signatures',
      'In-browser RSA-2048 key & certificate generation',
      'Upload existing .p12/.pfx certificates',
      'SHA-256 hash of document content',
      'Private key never stored or transmitted',
      'Verifiable in Adobe Reader / Acrobat',
      'Combine visible + cryptographic signature',
    ],
  },
  {
    slug: 'protect-pdf',
    name: 'Protect PDF',
    shortDescription: 'Password protect your PDF',
    longDescription: 'Add AES-256 password protection to PDF files. Set user and owner passwords, control permissions (print, copy, edit), and generate strong random passwords.',
    category: 'pdf',
    icon: '/icons/tools/protect-pdf.svg',
    primaryKeyword: 'password protect pdf',
    pageTitle: 'Password Protect PDF Online Free | Docukit',
    metaDescription: 'Add password protection to PDF files online for free. AES-256 encryption, permission controls, strength meter. 100% browser-based.',
    h1: 'Password Protect PDF Online for Free',
    relatedSlugs: ['unlock-pdf', 'sign-pdf', 'redact-pdf'],
    wasmDeps: ['pdf-lib'],
    faqs: [
      { q: 'What encryption standard is used?', a: 'AES-256 encryption per the PDF 2.0 specification — the strongest available PDF encryption standard.' },
      { q: 'What is the difference between user and owner passwords?', a: 'The user password is required to open the PDF. The owner password controls permissions (printing, copying, editing) — it can be set separately from the user password.' },
      { q: 'Can I restrict printing or copying?', a: 'Yes — use the permission checkboxes to control: Print, Copy Text, Edit Content, Fill Forms, Add Annotations, and Assemble Document.' },
      { q: 'Is the password stored anywhere?', a: 'No. Your password is used only in-browser to encrypt the PDF and is never transmitted or stored.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF file into the upload area.' },
      { title: 'Set your password', description: 'Enter a password (or generate a strong random one). Optionally set an owner password and restrict permissions.' },
      { title: 'Download protected PDF', description: 'Click "Protect & Download" — your PDF is now encrypted with AES-256.' },
    ],
    features: [
      'AES-256 encryption (PDF 2.0)',
      'User and owner passwords',
      'Permission controls (print, copy, edit, etc.)',
      'Password strength meter',
      'Random password generator',
      '100% client-side — password never transmitted',
    ],
  },
  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    shortDescription: 'Remove password from PDF',
    longDescription: 'Remove password protection from PDF files. Enter the password to decrypt your PDF and download an unlocked version.',
    category: 'pdf',
    icon: '/icons/tools/unlock-pdf.svg',
    primaryKeyword: 'unlock pdf',
    pageTitle: 'Unlock PDF — Remove Password Online Free | Docukit',
    metaDescription: 'Remove password protection from PDF files online for free. Enter the password, download unlocked PDF. 100% browser-based, private.',
    h1: 'Unlock PDF — Remove Password for Free',
    relatedSlugs: ['protect-pdf', 'compress-pdf', 'merge-pdf'],
    wasmDeps: ['pdf-lib'],
    faqs: [
      { q: 'Do I need the original password to unlock?', a: 'Yes — you must know the PDF\'s password. This tool decrypts PDFs for which you have the password; it is not a password cracker.' },
      { q: 'What does "unlock" do exactly?', a: 'It decrypts the PDF and saves a new version without password protection, so it can be opened without entering a password.' },
      { q: 'What if the PDF has permission restrictions only (no open password)?', a: 'Upload the PDF without entering a password. If it has only permission restrictions (owner password), Docukit will remove those restrictions.' },
      { q: 'Is this safe and private?', a: 'Yes — everything happens in your browser. Your PDF and password are never sent to any server.' },
    ],
    howToSteps: [
      { title: 'Upload your encrypted PDF', description: 'Drop the password-protected PDF into the upload area. The encryption is detected automatically.' },
      { title: 'Enter the password', description: 'Type the PDF\'s password. You can toggle visibility with the eye icon.' },
      { title: 'Download unlocked PDF', description: 'Click "Unlock & Download" to get your password-free PDF.' },
    ],
    features: [
      'Detects encryption automatically',
      'Removes user and owner passwords',
      'Shows original encryption details',
      'Instant decryption in-browser',
    ],
  },
  {
    slug: 'pdf-to-image',
    name: 'PDF to Image',
    shortDescription: 'Convert PDF pages to images',
    longDescription: 'Convert PDF pages to PNG, JPEG, WebP, or AVIF images at any DPI. Choose specific pages or convert all pages to a ZIP archive.',
    category: 'pdf',
    icon: '/icons/tools/pdf-to-image.svg',
    primaryKeyword: 'pdf to jpg',
    pageTitle: 'PDF to Image Online Free — PNG, JPG, WebP | Docukit',
    metaDescription: 'Convert PDF to image online for free. Export pages as PNG, JPEG, WebP, or AVIF at custom DPI. 100% browser-based, no uploads.',
    h1: 'Convert PDF to Image Online for Free',
    relatedSlugs: ['image-to-pdf', 'compress-image', 'compress-pdf'],
    wasmDeps: ['pdfjs'],
    faqs: [
      { q: 'What image formats can I export to?', a: 'PNG, JPEG, WebP, and AVIF. Each format has quality/compression options.' },
      { q: 'What DPI options are available?', a: '72 DPI (screen), 150 DPI (print), 300 DPI (high quality), or a custom value up to 600 DPI.' },
      { q: 'Can I export all pages at once?', a: 'Yes — exporting multiple pages creates a ZIP file with one image per page.' },
      { q: 'Why is PNG output large?', a: 'PNG is lossless. For smaller files, use JPEG or WebP with a quality setting around 85–90%.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF file into the upload area.' },
      { title: 'Configure output', description: 'Choose the image format, DPI, quality setting, and which pages to export.' },
      { title: 'Download images', description: 'Click "Convert & Download" — get individual images or a ZIP for multiple pages.' },
    ],
    features: [
      'PNG, JPEG, WebP, AVIF output',
      'Custom DPI up to 600',
      'Single page, all pages, or page range',
      'Page preview before download',
      'ZIP download for multi-page exports',
    ],
  },
  {
    slug: 'image-to-pdf',
    name: 'Image to PDF',
    shortDescription: 'Convert images to a PDF document',
    longDescription: 'Convert one or more images to a PDF. Supports JPEG, PNG, WebP, BMP, TIFF, SVG, and HEIC. Choose page size, image placement, margins, and more.',
    category: 'pdf',
    icon: '/icons/tools/image-to-pdf.svg',
    primaryKeyword: 'image to pdf',
    pageTitle: 'Image to PDF Online Free — JPG, PNG to PDF | Docukit',
    metaDescription: 'Convert images to PDF online for free. JPEG, PNG, WebP, HEIC supported. Choose page size and layout. 100% browser-based.',
    h1: 'Convert Images to PDF Online for Free',
    relatedSlugs: ['pdf-to-image', 'compress-pdf', 'merge-pdf'],
    wasmDeps: ['pdf-lib'],
    faqs: [
      { q: 'What image formats are supported?', a: 'JPEG, PNG, WebP, BMP, TIFF, SVG, and HEIC (iPhone photos).' },
      { q: 'Can I set a specific page size?', a: 'Yes — Fit Image (page matches image dimensions), A4, Letter, Legal, or custom dimensions.' },
      { q: 'Can I convert multiple images into a single PDF?', a: 'Yes — upload multiple images, reorder them by dragging, and they all become pages in one PDF.' },
      { q: 'What image placement options are available?', a: 'Center with margins, Stretch to fill, Fit within page (maintain aspect ratio), or Cover (smart crop to fill).' },
    ],
    howToSteps: [
      { title: 'Upload your images', description: 'Drop one or more image files. Drag to reorder them — each becomes a page in the PDF.' },
      { title: 'Configure layout', description: 'Choose page size, image placement, margins, and background color. Set per-image or global options.' },
      { title: 'Convert and download', description: 'Click "Convert & Download" to get your PDF.' },
    ],
    features: [
      'JPEG, PNG, WebP, BMP, TIFF, SVG, HEIC support',
      'Multi-image drag-and-drop reorder',
      'Fit Image, A4, Letter, Legal, custom page sizes',
      'Margin controls in mm or inches',
      'Per-image or global settings',
    ],
  },
  {
    slug: 'watermark-pdf',
    name: 'Watermark PDF',
    shortDescription: 'Add text or image watermarks to PDF',
    longDescription: 'Add customizable text or image watermarks to PDF pages. Control font, size, color, opacity, rotation, and placement. Apply to all pages, odd/even pages, or specific ranges.',
    category: 'pdf',
    icon: '/icons/tools/watermark-pdf.svg',
    primaryKeyword: 'add watermark to pdf',
    pageTitle: 'Add Watermark to PDF Online Free | Docukit',
    metaDescription: 'Add text or image watermarks to PDF files online for free. Custom font, opacity, rotation, placement. 100% browser-based.',
    h1: 'Add Watermark to PDF Online for Free',
    relatedSlugs: ['compress-image', 'edit-pdf', 'protect-pdf'],
    wasmDeps: ['pdf-lib', 'pdfjs'],
    faqs: [
      { q: 'Can I watermark specific pages only?', a: 'Yes — apply to all pages, odd pages, even pages, or a custom page range.' },
      { q: 'Can I use my company logo as a watermark?', a: 'Yes — switch to Image Watermark mode, upload your logo (PNG/SVG recommended for transparency), and adjust opacity and position.' },
      { q: 'Can I place the watermark behind the content?', a: 'Yes — use the layer toggle to place the watermark behind or on top of existing content.' },
      { q: 'Can I tile the watermark across the page?', a: 'Yes — the Repeated Grid option tiles the watermark across the entire page at a configurable spacing.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF file into the upload area.' },
      { title: 'Configure your watermark', description: 'Choose Text or Image watermark. Set font, size, color, opacity, rotation, and placement.' },
      { title: 'Apply and download', description: 'Preview the watermark on a sample page, then click "Apply & Download".' },
    ],
    features: [
      'Text and image watermarks',
      'Full opacity, rotation, and size control',
      'Single placement or tiled/repeated grid',
      'Apply to all, odd, even, or specific pages',
      'Layer behind or on top of content',
      'Live preview on sample page',
    ],
  },
  {
    slug: 'edit-pdf',
    name: 'Edit PDF',
    shortDescription: 'Annotate and edit PDFs visually',
    longDescription: 'Add text boxes, shapes, images, freehand drawings, highlights, and stamps to any PDF. Full annotation editor with Fabric.js canvas overlay. Save as flattened PDF or true PDF annotation objects.',
    category: 'pdf',
    icon: '/icons/tools/edit-pdf.svg',
    primaryKeyword: 'edit pdf online free',
    pageTitle: 'Edit PDF Online Free — Annotate & Add Text | Docukit',
    metaDescription: 'Edit PDF files online for free. Add text, shapes, images, highlights, stamps, and freehand drawings. 100% browser-based annotation editor.',
    h1: 'Edit PDF Online for Free',
    relatedSlugs: ['sign-pdf', 'redact-pdf', 'watermark-pdf'],
    wasmDeps: ['pdf-lib', 'pdfjs'],
    faqs: [
      { q: 'Can I edit existing text in a PDF?', a: 'This is an annotation/overlay editor — you can add new text on top of the PDF. Modifying existing PDF text streams is not supported (it requires re-parsing complex PDF content streams).' },
      { q: 'What annotation tools are available?', a: 'Text boxes, image overlays, emoji, shapes (rectangle, circle, line, arrow), freehand drawing, highlights, whiteout, and stamps (APPROVED, DRAFT, CONFIDENTIAL, etc.).' },
      { q: 'What is the difference between Flatten and Keep as Annotations?', a: 'Flatten permanently composites annotations into the page — they cannot be edited later. Keep as Annotations saves them as PDF annotation objects, viewable and editable in Adobe Reader.' },
      { q: 'Is there undo/redo?', a: 'Yes — Ctrl+Z / Ctrl+Shift+Z with up to 50 action history.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF into the upload area — pages render in the annotation editor.' },
      { title: 'Add annotations', description: 'Select a tool from the toolbar (text, shape, draw, stamp, etc.) and annotate your PDF pages.' },
      { title: 'Save and download', description: 'Choose Flatten (permanent) or Keep as Annotations, then click "Save & Download".' },
    ],
    features: [
      'Text boxes with font/size/color/style',
      'Shapes: rectangle, ellipse, line, arrow',
      'Freehand drawing with Bezier smoothing',
      'Highlight, whiteout, and stamp tools',
      'Image and emoji overlays',
      'Undo/redo (50 actions)',
      'Flatten or keep as PDF annotations',
    ],
  },
  {
    slug: 'add-page-numbers',
    name: 'Add Page Numbers',
    shortDescription: 'Add page numbers to PDF',
    longDescription: 'Add customizable page numbers to PDF files. Choose position, format (numeric, roman, alphabetic), font, size, color, and starting number.',
    category: 'pdf',
    icon: '/icons/tools/page-numbers.svg',
    primaryKeyword: 'add page numbers to pdf',
    pageTitle: 'Add Page Numbers to PDF Online Free | Docukit',
    metaDescription: 'Add page numbers to PDF files online for free. Choose position, format, font, and size. 100% browser-based.',
    h1: 'Add Page Numbers to PDF Online for Free',
    relatedSlugs: ['edit-pdf', 'watermark-pdf', 'merge-pdf'],
    wasmDeps: ['pdf-lib'],
    faqs: [
      { q: 'What position options are available?', a: 'Bottom-center (default), bottom-left, bottom-right, top-center, top-left, and top-right.' },
      { q: 'What number formats are supported?', a: '"1", "Page 1", "Page 1 of N", "1/N", Roman numerals (i, ii, iii), and alphabetic (a, b, c).' },
      { q: 'Can I skip the first few pages (e.g., cover and table of contents)?', a: 'Yes — set a starting page offset to skip the first N pages from numbering.' },
      { q: 'Does it handle mixed page sizes correctly?', a: 'Yes — page number positions are calculated per-page based on each page\'s individual dimensions.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF file into the upload area.' },
      { title: 'Configure page numbers', description: 'Choose position, format, font, size, color, starting number, and page range.' },
      { title: 'Apply and download', description: 'Preview on the first and last page, then click "Apply & Download".' },
    ],
    features: [
      '6 position options',
      'Numeric, Roman, and alphabetic formats',
      'Custom starting number',
      'Skip first N pages (for TOC/cover)',
      'Font, size, and color controls',
      'Live preview on first and last page',
    ],
  },
  {
    slug: 'crop-pdf',
    name: 'Crop PDF',
    shortDescription: 'Crop or trim PDF pages',
    longDescription: 'Crop PDF pages visually with drag handles or by entering exact margins. Auto-detect and remove white borders. Apply to one page or all pages.',
    category: 'pdf',
    icon: '/icons/tools/crop-pdf.svg',
    primaryKeyword: 'crop pdf',
    pageTitle: 'Crop PDF Online Free — Trim Pages | Docukit',
    metaDescription: 'Crop PDF pages online for free. Visual crop with drag handles or numeric input. Auto-crop whitespace. 100% browser-based.',
    h1: 'Crop PDF Pages Online for Free',
    relatedSlugs: ['compress-pdf', 'rearrange-pdf-pages', 'edit-pdf'],
    wasmDeps: ['pdf-lib', 'pdfjs', 'mupdf'],
    faqs: [
      { q: 'What is the difference between CropBox and Flatten modes?', a: 'CropBox hides content outside the crop area but keeps it in the file (reversible). Flatten mode permanently removes cropped content, producing a smaller file.' },
      { q: 'Can I crop individual pages differently?', a: 'Yes — enable "Custom per-page" mode to set different crop margins for each page.' },
      { q: 'What is Auto-crop whitespace?', a: 'It automatically detects white borders around the page content and removes them, like a document scanner trim.' },
      { q: 'Can I enter exact crop values?', a: 'Yes — use Numeric Input mode to enter precise top, right, bottom, and left margins in mm, inches, or PDF points.' },
    ],
    howToSteps: [
      { title: 'Upload your PDF', description: 'Drop your PDF file into the upload area.' },
      { title: 'Set crop area', description: 'Drag the crop handles on the page preview, or enter exact numeric margins. Use Auto-crop to detect white borders.' },
      { title: 'Apply and download', description: 'Choose CropBox (reversible) or Flatten (permanent), then click "Crop & Download".' },
    ],
    features: [
      'Visual crop with drag handles',
      'Numeric margin input (mm, inches, points)',
      'Auto-crop whitespace detection',
      'CropBox (reversible) or Flatten (permanent)',
      'Apply to current page, all pages, or custom range',
    ],
  },
  {
    slug: 'redact-pdf',
    name: 'Redact PDF',
    shortDescription: 'Permanently remove sensitive content',
    longDescription: 'Permanently redact sensitive information from PDFs. Text, images, and metadata in marked areas are completely destroyed — not just covered visually. True redaction via MUPDF.',
    category: 'pdf',
    icon: '/icons/tools/redact-pdf.svg',
    primaryKeyword: 'redact pdf',
    pageTitle: 'Redact PDF Online Free — Permanently Remove Content | Docukit',
    metaDescription: 'Permanently redact sensitive content from PDF files online for free. True redaction destroys underlying text and images. 100% browser-based.',
    h1: 'Redact PDF Online for Free',
    relatedSlugs: ['edit-pdf', 'protect-pdf', 'compress-pdf'],
    wasmDeps: ['pdf-lib', 'pdfjs', 'mupdf'],
    faqs: [
      { q: 'What makes this "true" redaction?', a: 'Text characters and image data in the redacted areas are removed from the PDF\'s content stream — not just covered with a black box. The underlying data is permanently destroyed.' },
      { q: 'Can I redact text by searching for it?', a: 'Yes — use "Find & Redact" to search for text, SSN patterns, email addresses, or custom patterns. All matching instances are highlighted for redaction.' },
      { q: 'Is this reversible?', a: 'No. Redaction is permanent and irreversible. A two-step workflow (mark → confirm) prevents accidental redaction.' },
      { q: 'Can metadata also be removed?', a: 'Yes — the "Full Metadata Strip" option removes XMP metadata, document info, and embedded file attachments.' },
    ],
    howToSteps: [
      { title: 'Upload and mark', description: 'Upload your PDF and draw rectangles over sensitive content. Use "Find & Redact" to automatically mark all instances of specific text.' },
      { title: 'Review markings', description: 'Review all marked areas (shown in translucent red). Click "Apply Redactions" when ready.' },
      { title: 'Confirm and download', description: 'Confirm the irreversible action in the warning dialog. Download your redacted PDF and verify the content is gone.' },
    ],
    features: [
      'True redaction — content permanently destroyed',
      'Find & Redact by text pattern',
      'Post-redaction verification',
      'Full metadata strip option',
      'Two-step safety workflow',
      'SHA-256 before/after comparison',
    ],
  },

  // ─── IMAGE TOOLS ────────────────────────────────────────────────────────
  {
    slug: 'compress-image',
    name: 'Compress Image',
    shortDescription: 'Reduce image file size',
    longDescription: 'Compress JPEG, PNG, WebP, AVIF, and HEIC images. Target a specific file size, use quality sliders, or reduce by percentage. Batch compress multiple images.',
    category: 'image',
    icon: '/icons/tools/compress-image.svg',
    primaryKeyword: 'compress image online',
    pageTitle: 'Compress Image Online Free — JPG, PNG, WebP | Docukit',
    metaDescription: 'Compress images online for free. JPEG, PNG, WebP, AVIF supported. Target file size, quality slider, or batch compression. 100% browser-based.',
    h1: 'Compress Images Online for Free',
    relatedSlugs: ['resize-image', 'convert-image', 'compress-pdf'],
    wasmDeps: ['image-wasm'],
    faqs: [
      { q: 'What image formats are supported?', a: 'JPEG, PNG, WebP, AVIF, BMP, TIFF, and HEIC (iPhone photos).' },
      { q: 'Can I target a specific file size?', a: 'Yes — enter a target size (e.g., "< 500KB") and Docukit iterates to find the right quality setting automatically.' },
      { q: 'What is EXIF stripping?', a: 'EXIF data contains metadata like GPS location, camera model, and capture time. Stripping it reduces file size and protects your privacy.' },
      { q: 'Can I compress multiple images at once?', a: 'Yes — upload multiple images for batch compression with the same settings. Download all as a ZIP.' },
    ],
    howToSteps: [
      { title: 'Upload your images', description: 'Drop one or more images into the upload area.' },
      { title: 'Set compression options', description: 'Choose quality, target file size, output format, and whether to strip EXIF data.' },
      { title: 'Compare and download', description: 'Use the before/after comparison slider, then download individually or as a ZIP.' },
    ],
    features: [
      'Quality slider and target file size mode',
      'JPEG, PNG, WebP, AVIF, HEIC support',
      'Before/after size comparison',
      'EXIF metadata stripping',
      'Batch compression with ZIP download',
      'Smart codec selection for photos vs illustrations',
    ],
  },
  {
    slug: 'resize-image',
    name: 'Resize Image',
    shortDescription: 'Resize images to exact dimensions',
    longDescription: 'Resize images by exact dimensions, percentage, or social media presets. Maintain aspect ratio or stretch freely. Crop, fit, fill, or cover resize modes.',
    category: 'image',
    icon: '/icons/tools/resize-image.svg',
    primaryKeyword: 'resize image',
    pageTitle: 'Resize Image Online Free — Exact Dimensions | Docukit',
    metaDescription: 'Resize images online for free. Exact dimensions, percentages, or social media presets. Aspect ratio lock, multiple fit modes. 100% browser-based.',
    h1: 'Resize Images Online for Free',
    relatedSlugs: ['compress-image', 'convert-image', 'crop-pdf'],
    wasmDeps: ['image-wasm'],
    faqs: [
      { q: 'What resize modes are available?', a: 'Fit (letterbox/pillarbox), Fill (crop to fill), Stretch (distort), and Cover (smart crop to fill without distortion).' },
      { q: 'Are there social media size presets?', a: 'Yes — presets for Instagram (Post, Story, Landscape), Twitter/X, LinkedIn, YouTube, and Facebook. All searchable.' },
      { q: 'Can I save custom presets?', a: 'Yes — save your own custom size presets which are stored in your browser\'s localStorage.' },
      { q: 'What happens if I resize larger than the original?', a: 'A warning is shown as upscaling reduces quality. You can still proceed if needed.' },
    ],
    howToSteps: [
      { title: 'Upload your image', description: 'Drop your image into the upload area.' },
      { title: 'Set target dimensions', description: 'Enter exact dimensions, a percentage, or choose a social media preset. Lock or unlock the aspect ratio.' },
      { title: 'Resize and download', description: 'Choose a fit mode and click "Resize & Download".' },
    ],
    features: [
      'Exact dimensions, percentage, or one-side resize',
      'Social media presets (Instagram, Twitter/X, LinkedIn, YouTube, Facebook)',
      'Fit, Fill, Stretch, Cover resize modes',
      'Aspect ratio lock',
      'Custom preset saving',
      'Batch resize',
    ],
  },
  {
    slug: 'convert-image',
    name: 'Convert Image',
    shortDescription: 'Convert image format',
    longDescription: 'Convert images between JPEG, PNG, WebP, AVIF, BMP, TIFF, ICO, GIF, and SVG formats. Batch convert multiple files to the same output format.',
    category: 'image',
    icon: '/icons/tools/convert-image.svg',
    primaryKeyword: 'convert image format',
    pageTitle: 'Convert Image Format Online Free — JPG, PNG, WebP | Docukit',
    metaDescription: 'Convert image formats online for free. JPEG, PNG, WebP, AVIF, HEIC, and more. Batch conversion. 100% browser-based.',
    h1: 'Convert Image Format Online for Free',
    relatedSlugs: ['compress-image', 'resize-image', 'pdf-to-image'],
    wasmDeps: ['image-wasm'],
    faqs: [
      { q: 'What formats can I convert between?', a: 'JPEG, PNG, WebP, AVIF, BMP, TIFF, ICO, GIF, and SVG (rasterized). HEIC (iPhone) to other formats is also supported.' },
      { q: 'Can I convert HEIC iPhone photos?', a: 'Yes — HEIC files from iPhones are supported and can be converted to JPEG, PNG, or WebP.' },
      { q: 'Can I convert multiple files at once?', a: 'Yes — upload multiple images and convert them all to the same target format. Download as a ZIP.' },
      { q: 'Does SVG conversion rasterize the vector?', a: 'Yes — SVG files are rasterized to a bitmap format. The output resolution is based on the SVG\'s natural size or a custom DPI setting.' },
    ],
    howToSteps: [
      { title: 'Upload your images', description: 'Drop one or more images in any supported format.' },
      { title: 'Choose output format', description: 'Select the target format and configure quality settings for the chosen format.' },
      { title: 'Convert and download', description: 'Click "Convert & Download" — get individual files or a ZIP for batch conversions.' },
    ],
    features: [
      'JPEG, PNG, WebP, AVIF, BMP, TIFF, ICO, GIF, SVG',
      'HEIC (iPhone) conversion',
      'Batch conversion to same format',
      'Per-format quality settings',
    ],
  },
  {
    slug: 'lock-image',
    name: 'Lock Image',
    shortDescription: 'Encrypt image with password',
    longDescription: 'Password-protect an image by encrypting it into a self-contained HTML file using AES-256-GCM. Share the HTML file — the recipient opens it in any browser and enters the password to view the image.',
    category: 'image',
    icon: '/icons/tools/lock-image.svg',
    primaryKeyword: 'encrypt image with password',
    pageTitle: 'Lock Image with Password — Encrypt Online Free | Docukit',
    metaDescription: 'Encrypt and password-protect images online for free. AES-256-GCM encryption into a self-contained HTML file. No server involved.',
    h1: 'Lock Image with Password for Free',
    relatedSlugs: ['view-once-image', 'compress-image', 'protect-pdf'],
    wasmDeps: [],
    faqs: [
      { q: 'How does the encrypted HTML file work?', a: 'The image is encrypted with AES-256-GCM and embedded in a self-contained HTML file. Opening it in any browser shows a password prompt — the correct password decrypts and displays the image.' },
      { q: 'Does this require an internet connection to open?', a: 'No — the HTML file is completely self-contained with all decryption code inline. It works offline in any modern browser.' },
      { q: 'Is the encryption strong?', a: 'Yes — AES-256-GCM with PBKDF2 key derivation (100,000 iterations, SHA-256). This is the same encryption used in banking and government systems.' },
      { q: 'What if someone enters the wrong password?', a: 'AES-GCM\'s authentication tag fails with an incorrect password, showing an "Incorrect password" error. There is no brute-force limit on the HTML file itself, so use a strong password.' },
    ],
    howToSteps: [
      { title: 'Upload your image', description: 'Drop your image into the upload area.' },
      { title: 'Set a password', description: 'Enter a strong password. The strength meter guides you.' },
      { title: 'Download encrypted HTML', description: 'Click "Lock & Download" — share the .html file. Recipients open it in a browser and enter the password to view the image.' },
    ],
    features: [
      'AES-256-GCM authenticated encryption',
      'PBKDF2 key derivation (100,000 iterations)',
      'Self-contained HTML — works offline',
      'No server involved — 100% client-side',
      'Works in any modern browser',
      'Password strength meter',
    ],
  },
  {
    slug: 'view-once-image',
    name: 'View-Once Image',
    shortDescription: 'Share an image that self-destructs after one view',
    longDescription: 'Create a secure link to share an image that can only be viewed once. The image is encrypted in your browser before upload — the decryption key is only in the link, never on our server. After the first view, the image is permanently deleted.',
    category: 'image',
    icon: '/icons/tools/view-once.svg',
    primaryKeyword: 'share image once self destruct',
    pageTitle: 'View-Once Image Link — Share & Self-Destruct | Docukit',
    metaDescription: 'Share images that self-destruct after one view. End-to-end encrypted before upload. Decryption key only in the link. Auto-deleted after viewing.',
    h1: 'Share an Image That Disappears After One View',
    relatedSlugs: ['lock-image', 'compress-image', 'convert-image'],
    wasmDeps: [],
    faqs: [
      { q: 'Can the server see my image?', a: 'No. The image is encrypted in your browser before it is uploaded. Only the encrypted blob is stored on our server. The decryption key is only in the URL fragment (after the #), which browsers never send to servers.' },
      { q: 'What happens after someone views it?', a: 'The encrypted image is immediately and permanently deleted from our server on the first request. There is no recovery.' },
      { q: 'What if no one views it?', a: 'The link expires automatically based on the TTL you set (1 hour, 6 hours, 24 hours, or 7 days). It is then deleted.' },
      { q: 'What is the maximum image size?', a: 'Images up to 10MB are supported.' },
    ],
    howToSteps: [
      { title: 'Upload your image', description: 'Drop the image you want to share (max 10MB).' },
      { title: 'Set expiry and create link', description: 'Choose how long the link stays active (1h–7d), then click "Create View-Once Link".' },
      { title: 'Share the link', description: 'Copy the generated link and send it to your recipient. The image is deleted from our servers after they view it.' },
    ],
    features: [
      'End-to-end encrypted before upload',
      'Decryption key only in the URL fragment',
      'Automatically deleted after first view',
      'Configurable expiry: 1h, 6h, 24h, or 7 days',
      'Works in any modern browser',
      'Max 10MB image size',
    ],
  },
];

export function getToolBySlug(slug: string): ToolDef | undefined {
  return TOOLS.find(t => t.slug === slug);
}

export function getRelatedTools(tool: ToolDef): ToolDef[] {
  return tool.relatedSlugs
    .map(slug => getToolBySlug(slug))
    .filter((t): t is ToolDef => t !== undefined);
}

export const PDF_TOOLS = TOOLS.filter(t => t.category === 'pdf');
export const IMAGE_TOOLS = TOOLS.filter(t => t.category === 'image');
